set_room_temperature:
  target:
    entity:
      integration: hitachi_yutaki
      domain: climate
  fields:
    temperature:
      required: true
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
          unit_of_measurement: "Â°C"
